In [1]:
%load_ext autoreload
%autoreload 2
from SRtools import prior_gen as pg
import numpy as np

In [2]:
gen = pg.PriorGen.prior_from_posterior_csv('test_prior.csv')

In [3]:
samp=gen.sample(100)

In [4]:
print(samp)

[[1.14824618e+00 2.23797435e+00 1.03904908e+03 6.35243061e+02]
 [4.25995315e-02 1.14341501e-01 1.35978613e+00 2.24108737e+01]
 [1.89773062e+00 5.78928883e+00 2.52355937e+03 9.73560744e+02]
 [1.54565714e+00 2.65058461e+00 1.74610384e+03 8.44413846e+02]
 [3.08388948e+00 8.27747485e+00 6.83388213e+03 1.60210152e+03]
 [1.19281864e-01 2.47850790e-01 1.02264987e+01 6.51653301e+01]
 [4.18714802e-01 6.73520824e-01 1.39335743e+02 2.34577294e+02]
 [1.47616460e+00 3.96217681e+00 1.61929060e+03 7.86414463e+02]
 [1.82745356e+00 4.60097232e+00 2.56613285e+03 9.73560744e+02]
 [1.23293126e+00 1.86026915e+00 1.13932320e+03 6.82093300e+02]
 [1.19281864e-01 2.47850790e-01 1.02264987e+01 6.51653301e+01]
 [6.77748822e+00 5.40003197e+01 2.62965774e+04 2.63643465e+03]
 [1.69461060e+00 1.97935486e+00 2.28254776e+03 9.73560744e+02]
 [2.59712614e+00 2.84545023e+00 5.45169727e+03 1.49205962e+03]
 [3.88419189e+00 3.09476899e+01 8.56452282e+03 1.49205962e+03]
 [5.47270723e+00 2.29917398e+01 1.94588992e+04 2.636434

In [11]:
gene=pg.PriorGenExtended.prior_from_posterior_csv_extended('test_prior.csv', seed=[1,1], variations=[0.7, 1.3], ndims=0, ndims_from_csv=3)

In [13]:
sampe = gene.sample(100)
print(sampe)

[[3.84136435e+02 7.96760067e+00 2.64322903e+02]
 [5.60231673e+02 1.16802932e+00 4.15246742e+02]
 [5.39485086e+02 1.94903705e+00 3.94920254e+02]
 [5.32741715e+02 2.51769589e+00 3.75588755e+02]
 [5.39485086e+02 2.07785812e+00 3.69357543e+02]
 [5.53228978e+02 1.32753302e+00 4.15246742e+02]
 [4.87840143e+02 3.94070411e+00 3.34082186e+02]
 [5.39485086e+02 2.36160618e+00 3.63229709e+02]
 [5.13013139e+02 3.05063783e+00 3.81925090e+02]
 [5.13013139e+02 3.25226890e+00 3.45449475e+02]
 [3.74593316e+02 7.96760067e+00 2.59937649e+02]
 [5.19506789e+02 3.25226890e+00 3.69357543e+02]
 [5.26082634e+02 2.51769589e+00 3.63229709e+02]
 [4.58103744e+02 5.42691221e+00 3.34082186e+02]
 [5.06600658e+02 3.05063783e+00 3.57203540e+02]
 [4.58103744e+02 5.42691221e+00 3.34082186e+02]
 [5.53228978e+02 1.50881822e+00 3.94920254e+02]
 [4.52377611e+02 5.42691221e+00 3.12457450e+02]
 [5.19506789e+02 3.25226890e+00 3.69357543e+02]
 [5.74504104e+02 1.09561495e+00 4.15246742e+02]
 [4.46723052e+02 5.09045969e+00 3.340821